---
format:
  html:
    toc: true
    toc-location: left
    number-sections: true
    self-contained: true
  docx:
    toc: false
    toc-title: Indice
    section-numbers: true
    reference-doc: "files/style.docx"
    output-file: "manuscript"
editor_options: 
  chunk_output_type: console
execute:
  echo: false
  warning: false
crossref:
  fig-title: Figure
  fig-prefix: Figure
  tbl-title: Table
  tbl-prefix: Table
# params:
#   template: ""
#   author: ""
#   advisor: ""
#   coadvisor: ""
#   location: ""
#   date: ""
#   institution: ""
#   faculty: ""
#   program: ""
#   type: ""
#   title: ""
---

```{r}
source("http://inkaverse.com/docs.r")
```

```{r}
rticle <- function(file = "draft.md", export = NULL, type = c("asis", "list")) {
  
  # file = "draft.md" ; export = NULL ; type = "list"
  
  type <- match.arg(type)

  if (is.null(export)) {
    export <- sub("\\.md$", "", file)
  }
  
  dir.create(export, recursive = T, showWarnings = F)
  
  section_break <- c(
  "```{=openxml}",
  "<w:p>",
  "  <w:pPr>",
  "    <w:sectPr/>",
  "  </w:pPr>",
  "</w:p>",
  "```"
  )
  
  gdoc <- file %>% 
    readLines(warn = F) %>% 
    tibble::enframe() %>% 
    dplyr::filter(!grepl("^#+ $", .data$value)) %>%  
    dplyr::filter(!grepl("^#$", .data$value)) %>% 
    dplyr::mutate(
    value = gsub(
      "!\\[(\\$\\$[^]]*\\$\\$|\\$[^]]*\\$)\\]\\[image[0-9]+\\]",
      "\\1",
      value
    ),
    value = gsub("\\\\\\\\", "\\\\", value),
    value = gsub("\\\\_", "_", value)
    ) %>%
    filter(!grepl("^\\|\\s*\\|$", value)) %>% 
    filter(!grepl("^\\|\\s*:?-+:?\\s*\\|$", value))
    
  
  tabs <- gdoc %>%
    mutate(
      table_start = grepl("^\\|\\s*Table\\s+[0-9]+\\s*:", value),
      table_id = cumsum(table_start)
    ) %>%
    filter(table_id > 0) %>%
    group_by(table_id) %>%
    mutate(
      is_table_line = grepl("^\\s*\\||^\\s*$", value),
      end_table = match(FALSE, is_table_line)
    ) %>%
    filter(row_number() < end_table | is.na(end_table)) %>%
    group_modify(~{
      .x %>%
    dplyr::add_row(value = section_break)
      }) %>% 
    ungroup() 
  
  figs <- gdoc %>%
    mutate(
      fig_start = grepl("^\\|\\s*!\\[\\]\\[image[0-9]+\\]\\s*\\|$", value),
      fig_id = cumsum(fig_start)
    ) %>%
    filter(fig_id > 0) %>%
    group_by(fig_id) %>%
    mutate(
      is_fig_line = grepl("^\\s*\\|", value),
      end_fig = match(FALSE, is_fig_line)
    ) %>%
    filter(row_number() < end_fig | is.na(end_fig)) %>%
    group_modify(~{
    dplyr::add_row(
      .x,
      value = section_break
    )
  }) %>%
    ungroup()
  
  txt <- gdoc %>%
    dplyr::filter(
    !name %in% tabs$name,
    !name %in% figs$name
  ) %>% 
    add_row(
    name = max(.$name, na.rm = TRUE) + 1,
    value = section_break
  )
  
  manuscript <- if (type == "asis") {
    
    gdoc
    
  } else if (type == "list") {
    
    list <- list(txt, figs, tabs) %>% 
      bind_rows() %>% 
      slice(-n())
  }
  
  qmd <- manuscript %>% 
    tibble::deframe() %>% 
    writeLines(con = file.path(export, gsub(pattern = ".md", replacement = ".qmd", x = file)))
  
  list.files(path = export
             , pattern = ".qmd"
             , full.names = T)
  
}
```


```{r}
#| eval: true
#| results: 'asis'

"draft.md" %>% 
  rticle(type = "list") %>% 
  knitr::knit_child(quiet = TRUE) %>% 
  cat(sep = '\n')
```

```{r}
knitr::knit_exit()
```












```{r}
#| label: setup

source("http://inkaverse.com/docs.r")
doc <- inti::gdoc2qmd(file = "article.zip"
                      , type = "listfull"
                      )
params <- doc$params
```

```{r}
#| eval: true
#| results: 'asis'

if(length(params) > 0) {
 cover <- list.files(path = "files/"
                    , pattern = paste0("cover-", params$template)
                    , full.names = T) %>% 
  knitr::knit_child(quiet = TRUE) %>% 
  cat(sep = '\n')
 }
```

```{r}
#| results: 'asis'

doc$path %>% 
  knitr::knit_child(quiet = TRUE) %>% 
  cat(sep = '\n')
```

```{r}
#| label: Image pdf to jpeg
#| eval: false

library(tidyverse)
library(magick)

pdf4pub <- list.files("files/", pattern = "Fig.*pdf", full.names = T) 

path <- "DisEd/"

imgs <- 1:length(pdf4pub) %>% map(\(x) {
  
  filename <- pdf4pub[x] %>% 
    basename() %>% 
    gsub(".pdf", "\\1.jpeg", .) 
  
  pdf4pub[x] %>% 
    image_read_pdf() %>% 
    image_write(format = "jpeg", file.path(path, filename))
  
})
```

```{r}
#| label: zip file
#| eval: false

tozip <- "manuscript" 

# unlink(paste0(tozip, ".zip"), recursive = T)

utils::zip(zipfile = paste0(tozip, ".zip")
                             , files = tozip
                             , flags = "-r9Xj"
                             )
```
